### ISSUE TITLE
upcase & downcase methods

### ISSUE THREAD

**Issue by salexzee** [salexzee/Easify#13]
easy enough

**Comment by salexzee** [comment]
README update needed!

**Comment by KingShimkus** [comment]
Dang, I was just about to submit a pull request that added those options.

**Comment by salexzee** [comment]
That's why in contribute.md I say to submit an issue or say something in an existing issue before you start working on any code. It'll prevent you from writing code that is already being written. Thanks for the interest though.

**Comment by KingShimkus** [comment]
Oke doke, I will be sure to do that next time.
