### ISSUE TITLE
randomcase method

### ISSUE THREAD

**Issue by salexzee** [salexzee/Easify#14]
Letters in a string are randomly set to upper and lowercase

**Comment by KingShimkus** [comment]
Seems like a cool feature, I will see about adding that.

**Comment by salexzee** [comment]
Great. I look forward to seeing your code :) :+1:

**Comment by salexzee** [comment]
You need to fork the project to be able to contribute code.

**Comment by KingShimkus** [comment]
I know that, haha. Hopefully you don't think I am that noobish. See here:  #17

**Comment by salexzee** [comment]
Good job man. And the test page looks 10x better :+1:
