### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by salexzee** [salexzee/Easify#16]
At some point this will be needed and I'll take care of it personally. This will be done in markdown for now.

**Comment by salexzee** [comment]
View the branch [here](https://github.com/salexzee/Easify/tree/styleguide)!

**Comment by KingShimkus** [comment]
I completely agree with the Style Guide! It couldn't be more perfect. :+1:

**Comment by salexzee** [comment]
Thanks! Still a work in progress, but it's coming along.
