### ISSUE TITLE
Adding string interpolation 

### ISSUE THREAD

**Issue by KingShimkus** [salexzee/Easify#22]
I think it would be neat to add a format method for easier and more beautiful code. For example:

``` javascript
"The {0} is {1}".format("cat", "cute"); //==> "The cat is cute"
```

I already have the code for it. What do you think?

**Comment by jaeming** [comment]
Kind of like string interpolation...

**Comment by KingShimkus** [comment]
No, but now that mention it, that would be way better.

**Comment by salexzee** [comment]
I think string interpolation would be great. This brings me back to the beautiful Ruby.

**Comment by salexzee** [comment]
Be prepared to see some Regex :100:

**Comment by KingShimkus** [comment]
Haha, I was. :) Look here: #24

**Comment by salexzee** [comment]
Great job! :+1:
