### ISSUE TITLE
Object cloning

### ISSUE THREAD

**Issue by KingShimkus** [salexzee/Easify#25]
I have an object `x`. I'd like to copy it as object `y`, such that changes to `y` do not modify `x`, essentially is what I am trying to go for here. So I could just do `e.clone(`_obj_`)` and it clones the object. Plus I already have an idea of what the code would look like. What do you guys think?

**Comment by salexzee** [comment]
Sounds good. I'm happy with you running with this idea.

**Comment by salexzee** [comment]
Great!
