### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by salexzee** [salexzee/Easify#32]
I just pushed a branch [NODE](https://github.com/salexzee/Easify/tree/node). There are still a lot of changes that need to be made before it can finalized, but I just wanted to show the progress. One of the big things is testing needs to be revamped. I'll be working on that in the coming days.

**Comment by KingShimkus** [comment]
What do you plan on doing with this? How do want to go about implementing your code into Node? Just curious because I want to help. Node is definitely one of my favs.

**Comment by salexzee** [comment]
If you looked at the branch I referenced, I don't think it actually needs to be as drastic as what I put together. I'd much rather keep the single file like we have on the master branch. I think it would be better just to use it for things like keeping track of and easily pulling in dependencies and automation tools. Things like [UglifyJS2](https://github.com/mishoo/UglifyJS2) for example. Also, to give people an easy and familiar way to pull Easify into their Node projects. All the modularization of Easify probably isn't necessary. The current Node branch will be removed pretty soon and then replaced.

**Comment by salexzee** [comment]
I just pushed a small update, putting Easify onto the NPM registry. There's not really any specific Node functionality right now. Main changes with this right now:
- Use terminal for testing with the following command: `npm run test`
- Can now use Node modules to help your workflow
- Dependency management will be much easier moving forward

I've globally installed UglifyJS2 just for the file compression but it's not needed in the dependencies.

`node_modules` is being ignored in `.gitignore`. The reason for this is to save space in the repo. No need to have a ton of modules saved in the repo, when any dependencies can be saved in `package.json` and then can be downloaded by the user by running `npm install` in the terminal.

To view this repo on NPM, visit https://www.npmjs.com/package/easifyjs
