### ISSUE TITLE
clear() method for arrays and objects

### ISSUE THREAD

**Issue by salexzee** [salexzee/Easify#42]
This should clear out all the contents of a given array or object.

**Comment by KingShimkus** [comment]
Working on it.

**Comment by salexzee** [comment]
Cool, I got lazy on this one lol. Also, it should be easy to clear out an object since it's passed to a function by reference. Different story with arrays though.

**Comment by salexzee** [comment]
I'm working on this for objects specifically. Already finished the functionality and now I'm just doing the README and testing.

**Comment by salexzee** [comment]
Clearing object complete. Not too worried about arrays.
